# Generated by Django 3.1.5 on 2021-02-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizrecords',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='quizrecords',
            name='start_time',
        ),
    ]
