# Generated by Django 3.1.5 on 2021-02-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210205_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrecords',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
